[project]
name = "drawing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "gdsfactory>=6.116.0",
    "numpy>=1.24.4",
<<<<<<< HEAD
    "pyaedt[all]>=0.6.60",
=======
    "pyaedt>=0.9.8",
>>>>>>> 546d1ccb8c395a9f8252c189756770819a192680
    "pydantic>=1.10.19",
    "shapely>=2.0.6",
]
